/// <reference types="tree-sitter-cli/dsl" />

const PREC = {
  ASSIGN: 1,
  OR: 2,
  AND: 3,
  EQUALITY: 4,
  RELATIONAL: 5,
  BIT_OR: 6,
  BIT_XOR: 7,
  BIT_AND: 8,
  SHIFT: 9,
  ADD: 10,
  MUL: 11,
  PREFIX: 12,
  POSTFIX: 13,
}
const commaSep = (rule) => optional(seq(rule, repeat(seq(",", rule)), optional(",")))
module.exports = grammar({
  name: 'dyn',
  extras: $ => [/\s/, $.comment],
  word: $ => $.identifier,
  conflicts: $ => [[$.primary, $.struct_literal]],
  rules: {
    source_file: $ => repeat(seq(optional(token('pub')), $.declaration)),
    declaration: $ => choice($.use, $.variable, $.const_variable, $.thread_local_variable, $.struct, $.enum, $.fn),
    use: $ => prec.right(seq(token('use'), $.string_, optional($.identifier))),
    variable: $ => seq($.identifier, choice($.type_qualifier, seq(optional($.type_qualifier), '=', $.expression))),
    const_variable: $ => seq(token('const'), $.variable),
    thread_local_variable: $ => seq(token('thread_local'), $.variable),
    struct: $ => seq(token('struct'), $.identifier, '{', commaSep($.struct_member), '}'),
    struct_member: $ => seq($.identifier, repeat(seq(',', $.identifier)), $.type_qualifier, optional(seq('=', $.expression))),
    enum: $ => seq(token('enum'), $.identifier, '{', commaSep($.enum_member), '}'),
    enum_member: $ => seq($.identifier, optional($.type_qualifier), optional(seq('=', $.expression))),
    fn: $ => seq(optional(token('inline')), token('fn'), $.identifier, '(', commaSep($.fn_param), ')', optional($.type), $.block),
    fn_param: $ => seq($.identifier, repeat(seq(',', $.identifier)), $.type_qualifier),
    block: $ => seq('{', repeat($.statement), '}'),
    statement: $ => choice($.return_, $.continue_, $.break_, $.variable, $.thread_local_variable, $.const_variable, $.if_, $.case_, $.for_, $.defer, $.call),
    return_: $ => prec.right(seq(token('return'), optional($.expression))),
    continue_: $ => seq(token('continue'), optional(seq(':', $.identifier))),
    break_: $ => seq(token('break'), optional(seq(':', $.identifier))),
    if_: $ => seq(token('if'), $.expression, $.block, optional($.else_)),
    else_: $ => seq(token('else'), choice($.if_, $.block)),
    case_: $ => seq(token('case'), $.expression, '{', commaSep($.case_arm), '}'),
    case_arm: $ => seq(choice('_', seq($.case_pattern, repeat(seq(',', $.case_pattern)))), '=>', $.block),
    case_pattern: $ => choice($.range, $.expression),
    for_: $ => seq(optional(seq($.identifier, ':')), token('for'), optional($.for_condition), $.block),
    for_condition: $ => choice(seq($.identifier, token('in'), $.expression), $.expression),
    defer: $ => seq(token('defer'), choice($.statement, $.block)),
    range: $ => seq($.expression, choice('..', '..='), $.expression),
    type_qualifier: $ => seq(':', $.type),
    type: $ => choice(seq($.identifier, repeat(seq('.', $.identifier))), $.array_type, $.pointer_type, $.primitive),
    array_type: $ => seq('[', optional($.number_), ']', $.type),
    pointer_type: $ => seq('*', $.type),
    primitive: _ => token(choice('i8', 'i16', 'i32', 'i64', 'u8', 'u16', 'u32', 'u64', 'f32', 'f64', 'bool')),
    expression: $ => choice($.literal, $.primary, $.unary_prefix, $.binary),
    primary: $ => choice($.identifier, $.unary_postfix, $.group, $.call, $.field_access, $.index),
    group: $ => seq('(', $.expression, ')'),
    binary: $ => choice(...[
      ['||', PREC.OR], ['&&', PREC.AND],
      ['==', PREC.EQUALITY], ['!=', PREC.EQUALITY],
      ['>', PREC.RELATIONAL], ['<', PREC.RELATIONAL],
      ['>=', PREC.RELATIONAL], ['<=', PREC.RELATIONAL],
      ['|', PREC.BIT_OR], ['^', PREC.BIT_XOR], ['&', PREC.BIT_AND],
      ['<<', PREC.SHIFT], ['>>', PREC.SHIFT],
      ['+', PREC.ADD], ['-', PREC.ADD],
      ['+%', PREC.ADD], ['-%', PREC.ADD],
      ['*', PREC.MUL], ['/', PREC.MUL], ['%', PREC.MUL], ['*%', PREC.MUL],
    ].map(([op, p]) => prec.left(p, seq($.expression, op, $.expression)))),
    unary_prefix: $ => prec(PREC.PREFIX, seq(choice('-', '&'), $.expression)),
    unary_postfix: $ => prec(PREC.POSTFIX, seq($.expression, '.*')),
    call: $ => seq($.primary, '(', commaSep($.expression), ')'),
    field_access: $ => seq($.primary, '.', $.identifier),
    index: $ => seq($.primary, '[', $.number_, ']'),
    literal: $ => choice($.bool_, $.null_, $.number_, $.string_, $.char_, $.struct_literal),
    struct_literal: $ => seq(choice(seq($.identifier, repeat(seq('.', $.identifier))), '.'), '{', commaSep(seq($.identifier, ':', $.expression)), '}'),
    bool_: _ => choice('true', 'false'),
    null_: _ => 'nil',
    number_: _ => token(choice(/0x[0-9A-Fa-f_]+/, /0b[01_]+/, /0o[0-7_]+/, /[0-9][0-9_]*\.[0-9][0-9_]*/, /[0-9][0-9_]*/)),
    string_: _ => token(seq('"', repeat(choice(/[^"\\\n]/, /\\./)), '"')),
    char_: _ => token(seq('\'', choice(/[^'\\\n]/, /\\./), '\'')),
    builtin_identifier: _ => /#[A-Za-z_][A-Za-z0-9_]*/,
    identifier: _ => /[A-Za-z_][A-Za-z0-9_]*/,
    comment: _ => token(choice(seq("//", /[^\n]*/), seq("/*", repeat(choice(/[^*]/, /\*[^/]/)), "*/"))),

    // TODO
    // macro stuff
    // add call to statement - has conflicts
  }
})
