const PREC = {
  or: 1,        // `a or handler` — lowest, guards everything to its left
  logical_or: 2,
  logical_and: 3,
  comparison: 4,
  range: 5,
  bit_or: 6,
  bit_xor: 7,
  bit_and: 8,
  shift: 9,
  add: 10,
  mul: 11,
  unary: 12,
  postfix: 13,
  composite: -1, // `Type{...}` loses to blocks in `if x {` via dynamic prec
};

module.exports = grammar({
  name: 'dyn',
  word: $ => $.identifier,
  extras: $ => [/\s/, ';', $.comment],
  conflicts: $ => [
    [$.decl_lhs, $.primary_expression],
    [$.decl_lhs, $.for],
    [$.struct_postfix, $.block],
    [$.enum_literal, $.field_postfix],
    [$.array_type, $.array_literal],
    [$.array_type, $.literal],
    [$.case, $.struct_postfix],
    [$.primary_expression, $.struct_init_member],
    [$.array_postfix, $.array_literal],
    [$.decl_lhs, $.struct_init_member],
    [$.call_arg, $.grouped]
  ],
  rules: {
    source_file: $ => repeat(seq(optional(token('pub')), $.declaration)),
    declaration: $ => seq($.decl_lhs, repeat(seq(',', $.decl_lhs)), '=', $.expression),
    decl_lhs: $ => choice(seq(optional(token('mut')), $.identifier, optional(seq(':', $.expression)))),
    statement: $ => choice($.declaration, $.for, $.return, $.break, $.continue),
    return: $ => prec.right(seq(token('return'), optional($.expression))),
    break: $ => prec.right(seq(token('break'), optional(seq(':', $.identifier)), optional($.expression))),
    continue: $ => prec.right(seq(token('continue'), optional(seq(':', $.identifier)))),
    for: $ => seq(optional(token('inline')), token('for'), optional(choice(seq($.identifier, repeat(seq(',', $.identifier)), ':', $.expression, repeat(seq(',', $.expression))), $.expression)), choice($.block, $.statement)),
    expression: $ => choice($.primary_expression, $.literal, $.binary, $.unary, $.compound_assign),
    primary_expression: $ => choice($.identifier, $.postfix, $.enum, $.struct, $.type, $.if, $.case, $.use, $.grouped),
    if: $ => prec.right(seq(token('if'), $.expression, $.result, optional(seq(token('else'), $.result)))),
    case: $ => seq(token('case'), $.expression, '{', repeat(seq(choice($.expression, '_'), ':', $.result)), '}'),
    struct: $ => seq(token('struct'), '{', optional(seq($.struct_member, repeat(seq(',', $.struct_member)))), '}'),
    struct_member: $ => seq($.identifier, repeat(seq(',', $.identifier)), ':', $.expression, optional(seq('=', $.expression))),
    enum: $ => seq(token('enum'), '{', optional(seq($.enum_member, repeat(seq(',', $.enum_member)))), '}'),
    enum_member: $ => seq($.identifier, optional(seq(':', $.expression))),
    enum_literal: $ => prec.right(seq('.', $.identifier, optional(seq('(', $.expression, ')')))),
    function: $ => seq('(', optional(seq($.identifier, repeat(seq(',', $.identifier)), ':', $.expression, optional(seq('=', $.expression)))), ')', optional($.expression), optional(choice($.block, seq(token('=>'), $.expression)))),
    binary: $ => choice(...[
      ['||', PREC.logical_or], ['&&', PREC.logical_and],
      ['==', PREC.comparison], ['!==', PREC.comparison],
      ['>', PREC.comparison], ['<', PREC.comparison],
      ['>=', PREC.comparison], ['<=', PREC.comparison],
      ['|', PREC.bit_or], ['^', PREC.bit_xor], ['&', PREC.bit_and],
      ['<<', PREC.shift], ['>>', PREC.shift],
      ['+', PREC.add], ['-', PREC.add],
      ['+%', PREC.add], ['-%', PREC.add],
      ['*', PREC.mul], ['/', PREC.mul], ['%', PREC.mul], ['*%', PREC.mul],
    ].map(([op, p]) => prec.left(p, seq($.expression, op, $.expression)))),
    compound_assign: $ => prec.right(seq($.identifier, choice('+=', '-=', '*=', '/=', '%=', '&=', '|=', '^=', '<<=', '>>='), $.expression)),
    unary: $ => prec(PREC.unary, seq(choice('&', seq('&', token('mut')), '-', '~', '!'), $.expression)),
    type: $ => choice($.array_type, $.pointer_type, $.builtin),
    builtin: $ => token(choice('void', 'module', 'any', 'type', /[iu][0-9]+/, 'f32', 'f64', 'bool')),
    array_type: $ => seq('[', optional(choice('_', $.int_literal)), ']', optional(token('mut')), $.expression),
    pointer_type: $ => seq('*', optional(token('mut')), $.expression),
    postfix: $ => prec(PREC.postfix, seq($.expression, choice($.pointer_postfix, $.field_postfix, $.array_postfix, $.call_postfix, $.struct_postfix))),
    pointer_postfix: _ => token('.*'),
    field_postfix: $ => seq('.', $.identifier),
    array_postfix: $ => seq('[', choice($.expression, '..'), ']'),
    call_postfix: $ => seq('(', optional(seq($.call_arg, repeat(seq(',', $.call_arg)))), ')'),
    call_arg: $ => seq(optional(seq($.identifier, ':')), $.expression),
    struct_postfix: $ => seq('{', optional(seq($.struct_init_member, repeat(seq(',', $.struct_init_member)))), '}'),
    struct_init_member: $ => seq($.identifier, ':', $.expression),
    block: $ => seq('{', optional(seq($.statement, repeat($.statement))), '}'),
    identifier: _ => /[A-Za-z_][A-Za-z0-9_]*/,
    use: $ => seq(token('use'), $.string_literal),
    grouped: $ => seq('(', $.expression, ')'),
    literal: $ => choice($.int_literal, $.float_literal, $.string_literal, $.char_literal, $.boolean_literal, $.enum_literal, $.array_literal, token('null')),
    directive: _ => /#[a-z_]+/,
    int_literal: _ => token(choice(/[0-9][0-9_]*/, /0[xX][0-9a-fA-F_]+/, /0[bB][01_]+/, /0[oO][0-7_]+/)),
    float_literal: _ => token(/[0-9][0-9_]*\.[0-9][0-9_]*([eE][+-]?[0-9]+)?/),
    string_literal: _ => token(seq('"', repeat(choice(/[^"\\]/, /\\./)), '"')),
    char_literal: _ => token(seq("'", choice(/[^'\\]/, /\\./), "'")),
    boolean_literal: _ => choice('true', 'false'),
    array_literal: $ => seq('[', optional(seq($.expression, repeat(seq(',', $.expression)))), ']'),
    result: $ => choice($.expression, $.statement, $.block),
    comment: _ => token(choice(seq('//', /[^\n]*/), seq('/*', /([^*]|\*+[^/*])*/, /\*+\//))),
  }
})
