const PREC = {
  or: 1,        // `a or handler` — lowest, guards everything to its left
  logical_or: 2,
  logical_and: 3,
  comparison: 4,
  range: 5,
  bit_or: 6,
  bit_xor: 7,
  bit_and: 8,
  shift: 9,
  add: 10,
  mul: 11,
  unary: 12,
  postfix: 13,
  composite: -1, // `Type{...}` loses to blocks in `if x {` via dynamic prec
};

module.exports = grammar({
  name: 'dyn',
  word: $ => $.identifier,
  extras: $ => [/\s/, ';', $.comment],
  conflicts: $ => [
  ],
  rules: {
    source_file: $ => repeat(seq(optional(token('pub')), $.declaration)),
    const: $ => token('const'),
    declaration: $ => choice(),
    statement: $ => choice($.for, $.return, $.break, $.continue),
    return: $ => prec.right(seq(token('return'), optional($.expression))),
    break: $ => prec.right(seq(token('break'), optional(seq(':', $.identifier)))),
    continue: $ => prec.right(seq(token('continue'), optional(seq(':', $.identifier)))),
    for: $ => seq(),
    expression: $ => choice(),
    binary: $ => choice(...[
      [token('or'), PREC.or],
      ['..', PREC.range], ['..=', PREC.range],
      ['||', PREC.logical_or], ['&&', PREC.logical_and],
      ['==', PREC.comparison], ['!=', PREC.comparison],
      ['>', PREC.comparison], ['<', PREC.comparison],
      ['>=', PREC.comparison], ['<=', PREC.comparison],
      ['|', PREC.bit_or], ['^', PREC.bit_xor], ['&', PREC.bit_and],
      ['<<', PREC.shift], ['>>', PREC.shift],
      ['+', PREC.add], ['-', PREC.add],
      ['+%', PREC.add], ['-%', PREC.add],
      ['*', PREC.mul], ['/', PREC.mul], ['%', PREC.mul], ['*%', PREC.mul],
    ].map(([op, p]) => prec.left(p, seq($.expression, op, $.expression)))),
    compound_assign: $ => prec.right(seq(choice($.identifier, $.postfix), choice('+=', '-=', '*=', '/=', '%=', '&=', '|=', '^=', '<<=', '>>='), $.expression)),
    unary: $ => prec(PREC.unary, seq(choice('&', seq('&', token('mut')), '-', '~', '!'), $.expression)),
    type: $ => choice($.array_type, $.pointer_type, $.builtin),
    builtin: _ => token(choice('void', 'module', 'any', 'type', /[iu][0-9]+/, 'f32', 'f64', 'bool')),
    array_type: $ => seq('[', optional(choice('_', $.int_literal)), ']', optional($.const), $.expression),
    pointer_type: $ => seq('*', optional(token('const')), $.expression),
    block: $ => seq('{', repeat($.statement), '}'),
    grouped: $ => seq('(', $.expression, ')'),
    identifier: _ => /[A-Za-z_][A-Za-z0-9_]*/,
    literal: $ => choice($.int_literal, $.float_literal, $.string_literal, $.char_literal, $.boolean_literal, token('nil')),
    char_literal: _ => token(seq("'", choice(/[^'\\]/, /\\./), "'")),
    boolean_literal: _ => choice('true', 'false'),
    string_literal: _ => token(seq('"', repeat(choice(/[^"\\]/, /\\./)), '"')),
    int_literal: _ => token(choice(/[0-9][0-9_]*/, /0[xX][0-9a-fA-F_]+/, /0[bB][01_]+/, /0[oO][0-7_]+/)),
    float_literal: _ => token(/[0-9][0-9_]*\.[0-9][0-9_]*([eE][+-]?[0-9]+)?/),
    comment: _ => token(choice(seq('//', /[^\n]*/), seq('/*', /([^*]|\*+[^/*])*/, /\*+\//))),
  }
})
