/// <reference types="tree-sitter-cli/dsl" />
const PREC = {
  ASSIGN: 1,
  OR: 2,
  AND: 3,
  EQUALITY: 4,
  RELATIONAL: 5,
  BIT_OR: 6,
  BIT_XOR: 7,
  BIT_AND: 8,
  SHIFT: 9,
  ADD: 10,
  MUL: 11,
  PREFIX: 12,
  POSTFIX: 13,
}
const commaSep = (rule) => optional(seq(rule, repeat(seq(",", rule)), optional(",")))
const commaSep1 = (rule) => seq(rule, repeat(seq(",", rule)), optional(","))

module.exports = grammar({
  name: "dyn",
  extras: ($) => [/\s/, $.comment],
  word: ($) => $.identifier,
  conflicts: ($) => [
    [$.type, $.expression],
    [$.call, $.struct_literal],
    [$.declaration, $.expression],
  ],
  rules: {
    source_file: ($) => repeat($._item),
    _item: ($) => seq(optional(token('pub'), choice($.use_, $.const_, $.global_, $.struct_, $.enum_, $.function_))),
    comment: (_) => token(choice( seq("//", /[^\n]*/), seq("/*", repeat(choice(/[^*]/, /\*[^/]/)), "*/"))),
    use_: ($) => seq("use", field("path", $.string_literal), optional(field("alias", $.identifier))),
    const_: ($) => seq("const", field("name", $.identifier), optional(seq(":", field("type", $.type))), "=", field("value", $.expression)),
    global_: ($) => seq(optional("thread_local"), field("name", $.identifier), ":", field("type", $.type)),
    struct_: ($) => seq("struct", field("name", $.identifier), "{", repeat( seq( field("field", commaSep1($.identifier)), ":", field("type", $.type), optional(","),),), "}"),
    enum_: ($) => seq("enum", field("name", $.identifier), "{", repeat( seq( field("variant", $.identifier), optional(seq(":", field("type", $.type))), optional(","),),), "}"),
    function_: ($) => seq("fn", field("name", $.identifier), "(", commaSep($.parameter), ")", optional(field("return_type", $.type)), field("body", $.block)),
    parameter: ($) => seq(field("name", $.identifier), ":", field("type", $.type)),
    type: ($) => choice($.pointer_type, $.array_type, $.slice_type, $.qualified_name),
    pointer_type: ($) => seq("*", optional("const"), field("type", $.type)),
    array_type: ($) => seq("[", field("size", $.expression), "]", field("element", $.type)),
    slice_type: ($) => seq( "[]", field("element", $.type),),
    qualified_name: ($) => seq( $.identifier, repeat(seq(".", $.identifier)),),
    block: ($) => seq("{", repeat($.statement), "}"),
    statement: ($) => choice($.block, $.declaration, $.assignment, $.if, $.case, $.for, $.labeled, $.defer, $.return, $.break, $.asm, $.call),
    declaration: ($) => seq(field("name", $.identifier), ":", field("type", $.type), optional(seq("=", field("value", $.expression)))),
    assignment: ($) => prec.right( PREC.ASSIGN, seq( field("left", $.expression), field("operator", choice("=", "+=", "-=", "*=", "/=", "%=")), field("right", $.expression),),),
    if: ($) => prec.right( seq( "if", field("condition", $.expression), field("consequence", $.block), optional( seq( "else", field("alternative", choice($.block, $.if)),),),),),
    case: ($) => seq( "case", field("value", $.expression), "{", repeat( seq( field("pattern", choice("_", $.expression)), "=>", field("body", choice($.block, $.expression)), optional(","),),), "}",),
    for: ($) => seq( "for", choice( field("body", $.block), seq(field("condition", $.expression), field("body", $.block)), seq( field("initializer", choice($.assignment, $.declaration)), ";", field("condition", $.expression), ";", field("update", $.assignment), field("body", $.block),), seq( field("binding", $.identifier), "in", field("iterable", $.expression), field("body", $.block),),),),
    labeled: ($) => seq( field("label", $.identifier), ":", field("statement", choice($.for, $.block)),),
    defer: ($) => seq( "defer", field("value", choice($.block, $.expression)),),
    return: ($) => seq( "return", optional(field("value", $.expression)),),
    break: ($) => seq( "break", optional(seq(":", field("label", $.identifier))),),
    asm: ($) => seq( "asm", "{", repeat(choice($.identifier, $.number_literal, ",", ".", ":", "\n")), "}",),
    expression: ($) => choice(
        $.identifier,
        $.qualified_name,
        $.number_literal,
        $.string_literal,
        $.char_literal,
        $.bool_literal,
        $.null_literal,
        $.parenthesized,
        $.unary,
        $.binary,
        $.call,
        $.field,
        $.index,
        $.deref,
        $.struct_literal,
        $.array_literal,
        $.builtin,
      ),
    parenthesized: ($) => seq("(", $.expression, ")"),
    unary: ($) => prec(PREC.PREFIX, seq( field("operator", choice("&", "-", "!", "~")), field("argument", $.expression),),),
    deref: ($) => prec.left(PREC.POSTFIX, seq( field("argument", $.expression), ".", "*",),),
    binary: ($) => choice(
        ...[
          [PREC.OR, "||"],
          [PREC.AND, "&&"],
          [PREC.EQUALITY, choice("==", "!=")],
          [PREC.RELATIONAL, choice("<", "<=", ">", ">=")],
          [PREC.BIT_OR, "|"],
          [PREC.BIT_XOR, "^"],
          [PREC.BIT_AND, "&"],
          [PREC.SHIFT, choice("<<", ">>")],
          [PREC.ADD, choice("+", "-")],
          [PREC.MUL, choice("*", "/", "%")],
        ].map(([precValue, operator]) =>
          prec.left(
            precValue,
            seq(
              field("left", $.expression),
              field("operator", operator),
              field("right", $.expression),
            ),
          ),
        ),
      ),
    call: ($) => prec( PREC.POSTFIX, seq( field("function", $.expression), "(", commaSep($.expression), ")",),),
    field: ($) => prec.left( PREC.POSTFIX, seq( field("object", $.expression), ".", field("field", $.identifier),),),
    index: ($) => prec.left( PREC.POSTFIX, seq( field("array", $.expression), "[", field("index", $.expression), "]",),),
    struct_literal: ($) => prec( PREC.POSTFIX, seq( field("type", $.type), "{", commaSep( choice( seq(field("name", $.identifier), ":", field("value", $.expression)), $.expression,),), "}",),),
    array_literal: ($) => seq( field("type", choice($.array_type, $.slice_type)), "{", commaSep($.expression), "}",),
    builtin: ($) => seq( field("name", $.builtin_identifier), choice( seq("(", commaSep($.expression), ")"), field("argument", $.type),),),
    bool_literal: (_) => choice("true", "false"),
    null_literal: (_) => "nil",
    number_literal: (_) => token(choice( /0x[0-9A-Fa-f_]+/, /0b[01_]+/, /0o[0-7_]+/, /[0-9][0-9_]*\.[0-9][0-9_]*/, /[0-9][0-9_]*/)),
    string_literal: (_) => token(seq( '"', repeat(choice(/[^"\\\n]/, /\\./)), '"')),
    char_literal: (_) => token(seq( "'", choice(/[^'\\\n]/, /\\./), "'")),
    builtin_identifier: (_) => /#[A-Za-z_][A-Za-z0-9_]*/,
    identifier: (_) => /[A-Za-z_][A-Za-z0-9_]*/,
  },
});
